# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M365 < Formula
  desc "Microsoft 365 CLI for one signed-in user"
  homepage "https://github.com/masonhuemmer/m365"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masonhuemmer/m365/releases/download/v0.5.0/m365_0.5.0_darwin_amd64.tar.gz"
      sha256 "4054cc7cb526ec379fc1664494f9c3cebec9a24f8762ffe89b16d513f0295940"

      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masonhuemmer/m365/releases/download/v0.5.0/m365_0.5.0_darwin_arm64.tar.gz"
      sha256 "49915513b357821a90bf01ebf9938776d5561f2b6ad67fb8d2155c9aee7f2b5d"

      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masonhuemmer/m365/releases/download/v0.5.0/m365_0.5.0_linux_amd64.tar.gz"
      sha256 "58fa9aa51818d647c4c21cab765544a5d1fb7cf7a827fde6435409cfad5d61b6"
      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masonhuemmer/m365/releases/download/v0.5.0/m365_0.5.0_linux_arm64.tar.gz"
      sha256 "abd77572d1874d8cebba8ece19b5ea6ae64186e913a4cef11451ec0269c42ea0"
      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  head "https://github.com/masonhuemmer/m365.git", branch: "main"

  test do
    assert_match "m365", shell_output("#{bin}/m365 --help")
    assert_match version.to_s, shell_output("#{bin}/m365 --version")
  end
end
